import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import Footer from "@/components/ui/footer";
import { Poppins } from "next/font/google";
import ReduxProvider from '@/app/providers'
import { ClerkProvider } from "@clerk/nextjs";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800","900"], 
});


export const metadata = {
  title: "Furniro",
  description: "Generated by create next app",
};

export default function RootLayout({   children,
}: Readonly<{
  children: React.ReactNode;
}>)  {
  return (
     <ClerkProvider>
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
      <ReduxProvider>
     
      
        <Navbar />
        {children}
        <Footer />
      
     
      </ReduxProvider>
      </body>
    </html>
     </ClerkProvider>
  );
}

